book_rec/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import login

app_name = 'book_rec'

urlpatterns = [
    url('^$', views.books,name='books'),

    url('^(?P<book_id>[0-9]+)$', views.detail, name='detail'),

    url('^register/$', views.UserFormView.as_view(), name='register'),

    url('^home/$', TemplateView.as_view(template_name='book_rec/home.html'), name='home'),

    url('^add/$', views.BookInput.as_view(), name='BookAdd'),

    url('^notes/$', views.notes,name='notes'),

    url('^gpa/$', TemplateView.as_view(template_name='book_rec/gpa.html'), name='gpa'),

    url('^about/$', TemplateView.as_view(template_name='book_rec/about.html'), name='about'),

    url('^login/$', views.login, name='login'),

    url('^course/$', TemplateView.as_view(template_name='book_rec/Category.html'), name='category'),

    url('^logout/$', views.logout,  name='logout'),

    url('^note_cat/$', TemplateView.as_view(template_name='book_rec/note.html'), name='note_cat'),
]

untitled1/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from book_rec import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    url('^$',TemplateView.as_view(template_name='book_rec/home.html')),
    url('^admin/', admin.site.urls),
    url('^book_rec/', include('book_rec.urls')),
    url('^detail/', views.detail),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_rec/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


sub_choice= [
        ('TOC','Theory of Computation'),
        ('SEDP','Software Engineering and Development'),
        ('A.Maths','Applied Mathematics'),
        ('A.Physics','Applied Physics'),
        ('EEE/BEE','Elements of Electrical Engineering'),
        ('ECP','Elements of Computer Engineering'),
        ('DEC','Digital Electronics And Communication'),
        ('STQA','Software Testing and Quality Assuarance'),
        ('AppChem','Applied Chemistry'),
        ('EVS','Environmental Studies'),
        ('AutoCAD','AutoCAD'),
        ('CAO','Computer Architecture and Organization'),
        ('DS','Discrete Structure'),
        ('DSA','Data Structure and Algorithm'),
        ('DBMS','DataBase Management System'),
        ('OOPS','Object Oriented and Programming System'),
        ('ADA','Analysis And Design of Algorithm'),
        ('MPI','MicroProcessor and Interfacing'),
        ('JAVA','Core Java'),
        ('POS','Principal of Operating System'),
        ('CG','Computer Graphics'),
        ('AJava','Advance Java'),
        ('WTCS','Web Technology and Cyber Security'),
    ]


class BookRecd(models.Model):
    subject= models.CharField(choices=sub_choice, max_length=6)
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    year_b = models.CharField(max_length=100)
    book_p = models.FileField()
    book_url = models.CharField(max_length=250)

    def get_absolute_url(self):
        return reverse('book_rec:detail', kwargs={'book_id':self.pk} )


    def __str__(self):
        return str(self.pk) + ' - ' + self.book_url + ' - ' + self.name + ' - ' + self.author


class NotesRecd(models.Model):
    title = models.CharField(max_length=100)
    subject = models.CharField(max_length=50)
    url = models.CharField(max_length=500)
    year = models.CharField(max_length=10)

    def __str__(self):
        return self.title + ' - ' + self.subject

book_rec/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm
from book_rec.models import BookRecd


sub_choice= [
        ('TOC','Theory of Computation'),
        ('SEDP','Software Engineering and Development'),
        ('A.Maths','Applied Mathematics'),
        ('A.Physics','Applied Physics'),
        ('EEE/BEE','Elements of Electrical Engineering'),
        ('ECP','Elements of Computer Engineering'),
        ('DEC','Digital Electronics And Communication'),
        ('STQA','Software Testing and Quality Assuarance'),
        ('AppChem','Applied Chemistry'),
        ('EVS','Environmental Studies'),
        ('AutoCAD','AutoCAD'),
        ('CAO','Computer Architecture and Organization'),
        ('DS','Discrete Structure'),
        ('DSA','Data Structure and Algorithm'),
        ('DBMS','DataBase Management System'),
        ('OOPS','Object Oriented and Programming System'),
        ('ADA','Analysis And Design of Algorithm'),
        ('MPI','MicroProcessor and Interfacing'),
        ('JAVA','Core Java'),
        ('POS','Principal of Operating System'),
        ('CG','Computer Graphics'),
        ('AJava','Advance Java'),
        ('WTCS','Web Technology and Cyber Security'),
    ]


class UserForms(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']


class UserFormsLin(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


#class BookRecdForm(ModelForm):
    #subject = forms.ChoiceField(choices=sub_choice, required=True )
    #class Meta:
        #model = BookRecd
        #widgets = {'subject': forms.TextInput(attrs={'placeholder': 'Subject:'}),
        #}

book_rec/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from .models import BookRecd, NotesRecd
from django.template import loader
from django.contrib.auth import authenticate
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import UserForms
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.models import auth
from django.contrib import messages


# Create your views here.


def books(request):
    all_books = BookRecd.objects.all()
    context = {'all_books': all_books,}
    return render(request, 'book_rec/index.html', context)


def home(request):
    context = {""}
    return render(request, 'book_rec/home.html', context)


def detail(request, book_id):
    try:
        book = BookRecd.objects.get(pk=book_id)
    except BookRecd.DoesNotExist:
         raise Http404("NO Book")
    return render(request, 'book_rec/detail.html', {'book': book})


class UserFormView(View):
    form_class = UserForms
    template_name = 'book_rec/regForm.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    auth_login(request, user)
                    return redirect('book_rec:home')

        return render(request, self.template_name, {'form': form})


class BookInput(CreateView):
    model = BookRecd
    #form_class = BookRecdForm
    fields = ['name', 'author', 'subject', 'year_b', 'book_p', 'book_url']


def notes(request):
    all_notes = NotesRecd.objects.all()
    context = {'all_notes': all_notes,}
    return render(request, 'book_rec/books.html', context)


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            return redirect('book_rec:home')
        else:
                messages.info(request, 'Invalid Credentials')
                return redirect('book_rec:login')
    else:
        return render(request, 'book_rec/login.html')


def logout(request):
    auth_logout(request)
    return redirect('book_rec:home')

templates/book_rec/BookRecd_form.html
{% extends 'book_rec/base.html' %}

{% block title %}Add Book{% endblock %}
<style>

</style>

{% block body %}

    <div class="container-fliud">
    <div class="row"  align="center">
        <div  align="center">
            <div class="panel panel-default ">

                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'book_rec/form-template.html' %}

                        <div align="center" class="form-group" align="center">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>

                </div>
                <div class="col-lg-6"></div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/book_rec/about.html
{% extends 'book_rec/base.html' %}

{% block title %} Notes Agents {% endblock %}

{% block body %}
<style>

</style>
</head>
<body>

<h2> "Meet The Team"</h2>
<br>

<div class="row">
  <div class="column">
    <div class="card">
      <img class="about" src="http://icons.iconarchive.com/icons/johanchalibert/mac-osx-yosemite/1024/finder-icon.png" alt="Md. Abudarda Khan" style="width:100%">
      <div class="container">
        <h2>Md. Abudarda Khan</h2>
        <p class="title">CEO & Founder</p>
        <p class="q">Interested in learning anything new and to working on a projects which not only tests me but also helps me learning new things</p>
        <pclass="q">khan.abudarda@gmail.com</p>
        <pclass="q"><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img class="about" src="https://cdn.pixabay.com/photo/2014/04/02/17/07/user-307993__340.png" alt="Simran Khetrapal" style="width:100%">
      <div class="container">
        <h2>Simran Khetrapal</h2>
        <p class="title q">Web Designer</p>
               <p class="q">I am ambitious and driven. I thrive on challenge and constantly set goals for myself, so I have something to strive toward. I’m not comfortable with settling, and I’m always looking for an opportunity to do better and achieve greatness</p>

        <p class="q">SimranKhetrapal1999@gmail.com</p>
        <p class="q"><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <img class="about" src="https://cdn1.iconfinder.com/data/icons/user-actions-13/24/action_people_user_windows-512.png" alt="Arun Pandey" style="width:100%">
      <div class="container">
        <h2>Arun Pandey</h2>
        <p class="title">Web Designer</p>
        <p class="q">Some text that describes me lorem ipsum ipsum lorem.</p>
        <p class="q">arunpandey2000@gmail.com</p>
        <p class="q"><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/book_rec/detail.html
{% extends 'book_rec/base.html' %}
{% block title %}{{ book.name }}{% endblock %}
{% block body %}
<img class="image" src="{{ book.book_p.url }}">

<h1>{{ book.name }}</h1>
<h2>{{ book.author }}</h2>

{% endblock %}

templates/book_rec/example.html
{% extends 'book_rec/base.html' %}

{% block head %}

<scrpit>

</script>

{% endblock %}


{% block body %}



{% endblock %}

templates/book_rec/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-lg-10 col-sm-10">
            <span class="text-danger small">T{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10 col-lg-10 class="field">{{ field }}</div>
    </div>
{% endfor %}

templates/book_rec/home.html
{% extends 'book_rec/base.html' %}
<head>
    <style>

    </style>

</head>
{% block title %} Notes Agents {% endblock %}

{% block body %}


<!--<form id="searchform" class="form-inline header " role="search">
<div class="row">
<div class="col-sm-8">
    <input type="search" name="s" id="s" placeholder="Search" class="form-control search-field">
</div>
<div class="col-sm-4">
    <button class="search-btn" type="button">Search </button>
</div>
</div>
</form>></button>
</form>-->

</div>


    <div class="row r">
        <div  class="col s12 m6 l3 el"   ><a href="{% url 'book_rec:note_cat' %}" ><img  class="responsive-img" src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/20bce1ea-cf9e-411b-96ad-2472b994876d/ddeo0mt-e07be24d-a190-4a66-9e43-c8f61ac88433.png/v1/fill/w_894,h_894,q_70,strp/notes1_by_maxmay98_ddeo0mt-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTA4MCIsInBhdGgiOiJcL2ZcLzIwYmNlMWVhLWNmOWUtNDExYi05NmFkLTI0NzJiOTk0ODc2ZFwvZGRlbzBtdC1lMDdiZTI0ZC1hMTkwLTRhNjYtOWU0My1jOGY2MWFjODg0MzMucG5nIiwid2lkdGgiOiI8PTEwODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.fJpjahX9ITsXWUixBgkwkzKTLZLOjaTRgsqYG-UJlxM"></a><h4 class="h">University Notes </h4> </div>
        <div class="col s12 m6 l3 el"  ><a href="#" > <img class="responsive-img" src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/20bce1ea-cf9e-411b-96ad-2472b994876d/ddern40-342095f2-5788-4f48-96db-f4145752492b.png/v1/fill/w_894,h_894,q_70,strp/q_a_a_by_maxmay98_ddern40-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTA4MCIsInBhdGgiOiJcL2ZcLzIwYmNlMWVhLWNmOWUtNDExYi05NmFkLTI0NzJiOTk0ODc2ZFwvZGRlcm40MC0zNDIwOTVmMi01Nzg4LTRmNDgtOTZkYi1mNDE0NTc1MjQ5MmIucG5nIiwid2lkdGgiOiI8PTEwODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.SHL5jCq-vxAhTWIJTs0TBnMaFEDtL5IvCdqG_ssKBBc" ><H4 class="h"> Question Papers </H4></div>
        <div class="col s12 m6 l3 el" ><a href="{% url 'book_rec:books' %}" ><img src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/20bce1ea-cf9e-411b-96ad-2472b994876d/ddermvs-a243e9c9-2930-4ad5-956c-edcb683ffff3.png/v1/fill/w_894,h_894,q_70,strp/book1_by_maxmay98_ddermvs-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTA4MCIsInBhdGgiOiJcL2ZcLzIwYmNlMWVhLWNmOWUtNDExYi05NmFkLTI0NzJiOTk0ODc2ZFwvZGRlcm12cy1hMjQzZTljOS0yOTMwLTRhZDUtOTU2Yy1lZGNiNjgzZmZmZjMucG5nIiwid2lkdGgiOiI8PTEwODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.ra-FuJ_mWOEmIm6bFF6coMA5YwrMr6RJIrAPdf7hXY8" class="responsive-img"><h4 class="h">Books</h4></div>
        <div class="col s12 m6 l3  el" ><a href="#" ><img src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/20bce1ea-cf9e-411b-96ad-2472b994876d/ddern6e-063b0dd9-d46b-454d-97b2-3e4e63bc44f4.png/v1/fill/w_894,h_894,q_70,strp/tie_by_maxmay98_ddern6e-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTA4MCIsInBhdGgiOiJcL2ZcLzIwYmNlMWVhLWNmOWUtNDExYi05NmFkLTI0NzJiOTk0ODc2ZFwvZGRlcm42ZS0wNjNiMGRkOS1kNDZiLTQ1NGQtOTdiMi0zZTRlNjNiYzQ0ZjQucG5nIiwid2lkdGgiOiI8PTEwODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.rLAcICbCR9b3MlPgL40q0QkP2pQqJE4CWJuDtIWFJL0" class="responsive-img"> <h4 class="h">Placements Content</h4></div>
      </div>


<footer class="panel-footer" id="footer">
    <div class="container">
      <div class="row">
        <section id="hours" class="col-md-12 col-lg-4">
          <span>Hours:</span><br>
          Sun-Thurs: 11:15am - 10:00pm<br>
          Fri: 11:15am - 2:30pm<br>
          Saturday Closed
          <hr class="visible-xs">
        </section>
        <section id="address" class="col-md-12 col-lg-4">
          <span>Address:</span><br>
          Sector – 43, Aravalli Hills, Delhi – Surajkund Road, Faridabad – 121004, <br>(Haryana), India

          <hr class="visible-xs">
        </section>
        <section id="testimonials" class="col-md-12 col-lg-4">
          <p>"The best Lecture notes providing site I've been to! And that's saying a lot, since I've been to many!"</p>
          <p>"Amazing Notes! Great service! Couldn't ask for more! I'll be back again and again!"</p>
        </section>
      </div>
       <div class="row r">
      <div class="col-md-3 col-lg-2 col-sm-12 col-xs-12   text-center" id="val">
         <a href="http://www.instagram.com/notesagents" data-toggle="tooltip"  id="social" title="Follow us on Instagram"><i class="fa fa-instagram" style="font-size:70px;color:#3b5999"></i></a>
      </div>
      <div class="col-md-3 col-lg-2 col-sm-12 col-xs-12   text-center" id="val">
         <a href="#" data-toggle="tooltip" title="Mail Us"><i class="fa fa-google"  id="social" style="font-size:70px;color:Red"></i></a>
      </div>
<div class="col-md-3 col-lg-2 col-sm-12 col-xs-12 text-center" id="val">
         <a href="https://t.me/Abudardakhan" data-toggle="tooltip" title="Message us"><i class="fa fa-telegram"  id="social" style="font-size:70px;color:#0077B5"></i></a>
      </div>
       <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12 text-center" id="val">
         <a href="#" data-toggle="tooltip" title="Follow us on Twitter"><i class="fa fa-twitter" id="social" style="font-size:70px;color:#55acee"></i></a>
      </div>


             <div class="col-md-12 col-lg-2 col-sm-12 col-xs-12 text-center" id="val">
         <a href="" data-toggle="tooltip" title="Follow us on Linkedin" ><i class="fa fa-linkedin"  id="social" style="font-size:70px;color:#1ab7ea"></i></a>

</div>

      </div>

      <div class="text-center">&copy; Copyright Notes Agents 2019</div>
    </div>
  </footer>

{% endblock %}

templates/book_rec/index.html
{% extends 'book_rec/base.html' %}
{% block title %}Books{% endblock %}
 <style type="text/css">
    .book {
padding: 15px 0 0 0;
margin:auto;
width:100px;
height:100px;
}
.book-img>.book-link:before {
content: '';
display: block;
width: 80%;
height: 1em;
background: rgba(0,0,0,.85);
border-radius: 50%;
position: absolute;
bottom:-10px;
-webkit-filter: blur(5px);
filter: blur(5px);
z-index:-5;
}
.shelf {
border-bottom: 30px solid #a5a5a5;
border-left: 20px solid transparent;
border-right: 20px solid transparent;
top: -15px;
z-index: -10;
}
.shelf:after {
content: '';
background: #333333;
height: 20px;
width: calc(100% + 40px);
position: absolute;
top: 30px;
left: 0;
right: 0;
z-index: 1;
margin: 0 -20px;
}
  </style>
  <script type="text/javascript">
      function addBook() {
 var body = document.getElementById("body").value;
 var div = document.createElement('div');

 var a=document.createElement('a');
div.setAttribute('class', 'col-xs-4 col-md-2 book-img');
a.setAttribute('href','link');
a.setAttribute('class','book-link');
var image=document.createElement('img');
image.setAttribute('src','img-src');
image.setAttribute('class','img-responsive book');
a.appendChild(image);
div.appendChild(a);
}

  </script>
{% block body %}
    {% if all_books %}


            {% for book in all_books %}
<div class="col-lg-3 col-xs-6 col-md-4 col-sm-3 image-hover-text-container">
         <div class="col-xs-12 image-hover-image" ><a href="{{ book.book_url }}" class="book-link "><img src="{{ book.book_p.url }}" class="img-responsive book"></a></div>
 <div class="image-hover-text">
    <div class="image-hover-text-bubble">
      <span class="image-hover-text-title"></span>
    " {{ book.name }} "<br>      {{ book.author }} <br> <a href="{{ book.book_url }}" class="book-link "><i class="material-icons bottom medium">cloud_download</i></a>
    </div>
  </div>
          <div class="col-lg-12 col-xs-12 col-md-12 col-sm-12  shelf">
             </div>




</div>







            {% endfor %}

    {% else %}
        <h3>No Books Availaible</h3>
    {% endif %}


{% endblock %}

templates/book_rec/login.html
{% extends 'book_rec/base.html' %}


{% block title %}Login{% endblock %}

{% block body %}

    <div class="container-fliud">
    <div class="row">
        <div class="col-sm-12 col-sm-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Enter Details</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                <form class="form-horizontal" id="form" role="form" action="" method="post">
                    {% csrf_token %}
                    User-name:
                    <input type= "text" name="username" placehlder="username"><br>
                    Password:
                    <input type= "password" name="password" placehlder="password"><br>


                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                </form>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/book_rec/note.html
{% extends 'book_rec/base.html' %}



{% block body %}
<div class="n_img">

 <div class="main_box ">
    <div class="z-depth-0 cs " id="ss"><a href="{% url 'book_rec:notes' %}" class="">Computer Science Engineering</a></div>
    <!-- <Div class="divider"></Div> -->
    <div class="section cs" ><a href="#!" class="">Mechanical Engineering</a></div>
     <!--<Div class="divider"></Div> -->
    <div class="section z-depth-0 cs"><a href="#!" class="">Civil Engineering</a></div>
     <!--<Div class="divider"></Div> -->
    <div class="section cs"><a href="#!" class="">Electical Engineering</a></div>
     <!--<Div class="divider"></Div> -->
    <div class="section z-depth-0 cs"><a href="#!" class="">Electronics Engineering</a></div>
     <!--<Div class="divider"></Div> -->
    <div class="section cs" ><a href="#!" class="">Aeronautical Engineering</a></div>
     <!--<Div class="divider"></Div> -->
    <div class="section z-depth-0 cs"><a href="#!" class="">Automobile Engineering</a></div>
     <!--<Div class="divider"></Div> -->
 </div>

 </div>

 <div class=" row ">
    <div class="size col s12 m6 l4 "> <img src="https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"><h3>Computer Science Engineering</h3></h3></div>
    <div class="size col s12 m6 l4 "> <img src="https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"><h3>Civil Engineering</h3></h3></div>
     <div class="size col s12 m6 l4 "> <img src="https://images.pexels.com/photos/159298/gears-cogs-machine-machinery-159298.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"><h3>Mechanical Engineering</h3></h3></div>
     <div class="size col s12 m6 l4 "> <img src="https://images.pexels.com/photos/65623/vehicle-chrome-technology-automobile-65623.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"><h3>Civil Engineering</h3></h3></div>

</div>

{% endblock %}

templates/book_rec/regForm.html
{% extends 'book_rec/base.html' %}
<style>
    .panel-body{
        display:content;

    }
</style>


{% block title %}Registration{% endblock %}

{% block body %}
<body class="background">
    <div class="container-fliud">
    <div class="row">
        <div class="col-sm-12 col-sm-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create new Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                <form class="form-horizontal" role="form" action="" method="post">
                    {% csrf_token %}
                    {% include 'book_rec/form-template.html' %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</body>
{% endblock %}